# Dependabot configuration for automated dependency updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Europe/London'
    open-pull-requests-limit: 10
    reviewers:
      - 'paulstakem'
    assignees:
      - 'paulstakem'
    commit-message:
      prefix: 'chore(deps)'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'automated'
    # Group non-security updates together
    groups:
      development-dependencies:
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'
      production-dependencies:
        dependency-type: 'production'
        update-types:
          - 'minor'
          - 'patch'
    # Always create individual PRs for major updates and security updates
    ignore:
      # Ignore specific packages if needed
      # - dependency-name: "package-name"
      #   versions: ["1.x", "2.x"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Europe/London'
    open-pull-requests-limit: 5
    reviewers:
      - 'paulstakem'
    assignees:
      - 'paulstakem'
    commit-message:
      prefix: 'chore(ci)'
      include: 'scope'
    labels:
      - 'ci'
      - 'dependencies'
      - 'automated'
